### ISSUE TITLE
SPIKE: Research/test starting MySQL container with via docker compose

### ISSUE THREAD

**Issue by m-e-w** [m-e-w/steam_bi#23]
https://stackoverflow.com/questions/64469458/dockerfile-run-a-init-sql-file-for-setting-up-tables

As part of the ongoing effort to simplify / automate the deployment process, we should test out using docker-compose to start a container initialized with our schema. 

Example docker compose file: 
```
version: '3.3'
services:
  database:
    image: mysql
    volumes:
       - "./sql-scripts:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_DATABASE: stock_app
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
```

> Whenever you update your sql script you would need to recreate the containers with docker-compose up -d --force-recreate. By design the mysql image will run any sql files found in the "/docker-entrypoint-initdb.d" folder so you should not have to manually run those every time you recreate the containers.

This may also be helpful as we will likely want to have a sanitized compose file and keep the actual MySQL password in a seperate .env file.

https://docs.docker.com/compose/environment-variables/
